### ISSUE TITLE
Download and store prior source measurements

### ISSUE THREAD

**Issue by talister** [LCOGT/neoexchange#52]
In order to support operations with NEO candidates where:
1) recoveries on the LCOGT Network need to be combined with the discovery and prior follow-up observations to confirm successful recovery and check astrometric residuals, 
2) maintain access to the above data in the case of objects which are not NEOs which vanish from the NEOCP for at least a week
3) provide the foundation of the future infrastructure to store and report astrometric and photometric measurements made with the LCOGT NEO Follow-up Network

we need to able to support and perform the following tasks:
- [x] create models to handle observed frames (happened in #46 ) and store source measurements
- [x] design a data model that is able to handle the existing MPC 1992 80 column format (http://www.minorplanetcenter.net/iau/info/OpticalObs.html) and the future ADES XML standard (http://www.minorplanetcenter.net/mpec/K15/K15O06.html)
- [x] create a parser and management command to ingest existing files of measurements for previously observed candidates
- [x] synthesize and display MPC 80-column format lines from the stored source measurements (in #49 )
- [x] create Frame entries from our observed FITS frames as part of the Block updating process
- [x] Download and store observations from the NEOCP for candidates
- [x] Handle `S/s` format satellite observations from e.g. `C51` (NEOWISE)
- [x] Handle and search for Bodies with a packed designations
- [x] Allow upload of results from Astrometrica through either a web form or file reading (maybe) - covered in #49
